### ISSUE TITLE
Add Dockerfile for simple CKAN deployment.

### ISSUE THREAD

**Issue by DavidLemayian** [CodeForAfricaLabs/openAFRICA#1]
This should allow deployment of a vanilla CKAN instance.

This can be based on CKAN's own [Dockerfile](https://github.com/ckan/ckan/blob/master/Dockerfile)

**Comment by shemogumbe** [comment]
I suppose this should be completed as an update to the readme, by perhaps adding **Deployment** section

**Comment by DavidLemayian** [comment]
@shemogumbe Yeah, and any improvements that can be done to the file.
