### ISSUE TITLE
Add Data Request button on openafrica home page.

### ISSUE THREAD

**Issue by andela-onnenanya** [CodeForAfricaLabs/openAFRICA#6]
### Currently:
When you install ckanext-datarequest on your ckan instance, it shows the button for DATAREQUEST. But once ckanext-openafrica is installed, the button is overridden.
Navigating to` /datarequest` show the page for requesting for dataset but the button is missing on the home page. see https://africaopendata.org/datarequest

### Desired Behaviour: 
A user should be able to see the datarequest button on the home page, which when clicked, should navigate to `/datarequest`.

### Why This Issue is Important:
Without the button, the user may not have any clue that datasets can be requested for. Moreover, a user who is aware of datarequest will not have to type `/datarequest` but can easily navigate to the page by clicking on the button.

### Notes:

- This issue can easily be handled by replicating the **`Suggest a dataset`** button shown at the button when no dataset is found for a user's search.
- Since ckanext-datarequest adds the button, it seems like a bug when the button does not appear after installing ckanext-openafrica

**Comment by shemogumbe** [comment]
So, the idea is to make users aware that they can request for a dataset.

**Comment by DavidLemayian** [comment]
Thanks @andela-onnenanya. This issue should be in https://github.com/CodeForAfrica/ckanext-openafrca/issues . Let's also ensure there is a way to check if data requests extension is activated before it shows the link to avoid 404 in a case where it isn't.

**Comment by andela-onnenanya** [comment]
@shemogumbe Exactly, to make users aware of the feature.

@DavidLemayian  Ok, I've moved the issue to  https://github.com/CodeForAfrica/ckanext-openafrca/issues
