### ISSUE TITLE
Add feature to enable users favourite datasets so they can easily find them

### ISSUE THREAD

**Issue by andela-iukwuoma** [CodeForAfricaLabs/openAFRICA#7]
Users might find datasets that they believe can be useful to them someday but not being able to add the datasets to a list of Favourites makes it difficult to remember such datasets. A feature which enable users to add datasets to a Favourites list will assist them in keeping track of every dataset that they have interest in.

**Comment by shemogumbe** [comment]
I find this to be a great idea, this gives users a record of datasets they will need to refer to in future even if they do not want them at the present moment

**Comment by DavidLemayian** [comment]
I think this is a good idea. I've moved this issue here - https://github.com/CodeForAfricaLabs/ckanext-followy/issues/1
